### ISSUE TITLE
Configuration files???

### ISSUE THREAD

**Issue by bigsmokeDev** [boxDev623/Crystal#1]
soo what is your plan for configuration files, .cfg or .lua files???

**Comment by boxDev2008** [comment]
Sorry for the late response. What do you mean exactly by configuration files? For building, theming or something else?

**Comment by bigsmokeDev** [comment]
customizing the editor in general (themes, settings)

**Comment by boxDev2008** [comment]
for now I think .ini files are ideal for this

**Comment by bigsmokeDev** [comment]
is there gonna be some kind of documentation for configuring the editor?

**Comment by boxDev2008** [comment]
for color themes probably. for general settings there will just be an easy to use gui window in the editor that writes to the file

**Comment by ms2010gamer** [comment]
pretty nice, this is using imgui so probably imgui colors right?

**Comment by ms2010gamer** [comment]
pretty cool 😎

**Comment by bigsmokeDev** [comment]
pretty cool 😎
